Patch: Case Senstivity

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -77,11 +77,11 @@ jobs:
           export PS4='+ $(date "+%s.%N") '
           
           echo "Running Profiled Build..."
-          bash -x ./build.sh --platform Android --project-name "${APP_NAME}" > script_profile.log 2>&1
+          bash -x ./build.sh --platform android --project-name "${APP_NAME}" > script_profile.log 2>&1
           
           echo "Running Profiled Upload..."
           # If this fails, we 'cat' the log so you can see the error in GitHub
-           bash -x ./upload.sh Android "${APP_NAME}.apk" >> script_profile.log 2>&1 || (echo "--- ERROR DETECTED IN LOG ---" && tail -n 20 script_profile.log && exit 1)
+           bash -x ./upload.sh android "${APP_NAME}.apk" >> script_profile.log 2>&1 || (echo "--- ERROR DETECTED IN LOG ---" && tail -n 20 script_profile.log && exit 1)
 
       - name: Upload Profile Log
         if: always()
